# Generated by Django 3.1.4 on 2021-06-14 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studl', '0003_auto_20210614_1838'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studluser',
            name='manages_employer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='studl.employer'),
        ),
    ]
