# Generated by Django 3.1.4 on 2021-06-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studluser_manages_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studluser',
            name='manages_employer',
        ),
    ]
