# Generated by Django 3.1.4 on 2021-06-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='employer',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='duration',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='free_positions',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='payment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='schedule',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
