# Generated by Django 3.1.4 on 2021-06-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studl', '0002_auto_20210103_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='address',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Street',
        ),
    ]
