# Generated by Django 3.1.4 on 2021-06-14 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studl', '0004_employerrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerrating',
            name='employer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='studl.employer'),
        ),
        migrations.AlterField(
            model_name='employerrating',
            name='rating',
            field=models.IntegerField(default='3'),
        ),
        migrations.AlterField(
            model_name='employerrating',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
